### ISSUE TITLE
Warn or prevent having multiple configurations with the same name

### ISSUE THREAD

**Issue by leehambley** [leehambley/mitre#28]
Given a config like this:

```
---
a:
  _runner: foo
b:
  _runner: foo
a: 
  _runner: bar
```

I think the second declaration of `a:` would silently overwrite the first, and could be potentially confusing. I think that this should be a fatal config error.
